# -*- coding: utf-8 -*-
"""BankNote.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I5ybzlCBX4xbwONwbp2nmxel8VG9UB9q
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.linear_model import LogisticRegression
import pickle

dataset = pd.read_csv('BankNote.csv')

X = dataset.iloc[:, :3]
y = dataset.iloc[:, -1]

LR=LogisticRegression()

LR.fit(X,y)

pickle.dump(LR, open('Banknote.pkl','wb'))

model = pickle.load(open('Banknote.pkl','rb'))

print(model.predict([[1, 1, 2]]))

